services:

  # =========================
  # Backend
  # =========================
  backend:
    build:
      context: ./ecommerce-fastapi
      dockerfile: Dockerfile

    container_name: ecommerce_backend

    restart: always

    ports:
      - "8000:8000"

    env_file:
      - ./ecommerce-fastapi/.env.docker

    volumes:
      - ./ecommerce-fastapi:/app

    depends_on:

      redis:
        condition: service_healthy

    command: ./scripts/docker-entrypoint.sh

    networks:
      - ecommerce_network


  # =========================
  # Frontend
  # =========================
  frontend:
    build:
      context: ./ecommerce-frontend
      dockerfile: Dockerfile

    container_name: ecommerce_frontend

    restart: always

    ports:
      - "5173:5173"

    volumes:
      - ./ecommerce-frontend:/app
      - /app/node_modules

    depends_on:
      - backend

    networks:
      - ecommerce_network


 

  # =========================
  # Redis
  # =========================
  redis:
    image: redis:7-alpine

    container_name: ecommerce_redis

    restart: always

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 20

    networks:
      - ecommerce_network


  # =========================
  # Prometheus
  # =========================
  prometheus:
    image: prom/prometheus

    container_name: ecommerce_prometheus

    restart: always

    ports:
      - "9090:9090"

    volumes:
      - ./ecommerce-fastapi/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml

    depends_on:
      - backend

    networks:
      - ecommerce_network


  # =========================
  # Grafana
  # =========================
  grafana:
    image: grafana/grafana

    container_name: ecommerce_grafana

    restart: always

    ports:
      - "3001:3000"

    volumes:
      - ./ecommerce-fastapi/grafana/provisioning:/etc/grafana/provisioning
      - ./ecommerce-fastapi/grafana/dashboards:/var/lib/grafana/dashboards

    depends_on:
      - prometheus

    networks:
      - ecommerce_network


volumes:
  redis_data:


networks:
  ecommerce_network: